export const S = {
  app: { fontFamily: "'Geist', sans-serif", background: "var(--c-bg)", minHeight: "100dvh", color: "var(--c-text)" },
  mono: { fontFamily: "'Geist Mono', monospace" },
  nav: {
    background: "var(--c-nav)",
    borderBottom: "1px solid var(--c-border)",
    padding: "0 24px",
    display: "flex",
    alignItems: "center",
    gap: 0,
    position: "sticky",
    top: 0,
    zIndex: 100,
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
  },
  navBrand: { fontFamily: "'Geist'", fontWeight: 800, fontSize: 15, color: "var(--c-accent)", letterSpacing: "0.05em", padding: "16px 0", marginRight: 32, whiteSpace: "nowrap" },
  navTab: (active) => ({
    padding: "16px 18px",
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: "0.02em",
    cursor: "pointer",
    color: active ? "var(--c-accent)" : "var(--c-muted)",
    borderBottom: active ? "2px solid var(--c-accent)" : "2px solid transparent",
    background: "none",
    border: "none",
    transition: "color .15s",
    whiteSpace: "nowrap",
  }),
  page: { padding: "28px 28px 60px", maxWidth: 1100, margin: "0 auto" },
  pageTitle: { fontWeight: 700, fontSize: 22, color: "var(--c-text)", marginBottom: 4, letterSpacing: "-0.02em" },
  pageSub: { fontSize: 13, color: "var(--c-muted)", marginBottom: 28, fontFamily: "'Geist Mono'" },
  card: {
    background: "var(--c-card)",
    border: "1px solid var(--c-border)",
    borderRadius: 16,
    padding: 20,
    boxShadow: "0 1px 3px rgba(0,0,0,0.1), 0 1px 2px rgba(0,0,0,0.06)",
  },
  cardTitle: { fontSize: 11, fontWeight: 600, letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--c-muted)", marginBottom: 12 },
  statVal: { fontFamily: "'Geist Mono'", fontSize: 26, fontWeight: 600, color: "var(--c-text)", lineHeight: 1, letterSpacing: "-0.02em" },
  statLabel: { fontSize: 12, color: "var(--c-muted)", marginTop: 5, letterSpacing: "0.04em" },
  input: {
    background: "var(--c-input-bg)",
    border: "1px solid var(--c-input-border)",
    borderRadius: 10,
    color: "var(--c-text)",
    padding: "10px 14px",
    fontSize: 14,
    fontFamily: "'Geist Mono'",
    outline: "none",
    width: "100%",
    transition: "border-color .15s, box-shadow .15s",
  },
  select: {
    background: "var(--c-input-bg)",
    border: "1px solid var(--c-input-border)",
    borderRadius: 10,
    color: "var(--c-text)",
    padding: "10px 14px",
    fontSize: 14,
    fontFamily: "'Geist Mono'",
    outline: "none",
    width: "100%",
    transition: "border-color .15s, box-shadow .15s",
  },
  btn: (variant = "primary") => ({
    padding: variant === "sm" ? "5px 12px" : "10px 18px",
    fontSize: variant === "sm" ? 11 : 13,
    fontWeight: 600,
    fontFamily: "'Geist'",
    borderRadius: variant === "sm" ? 8 : 10,
    cursor: "pointer",
    border: "none",
    background:
      variant === "danger" ? "var(--c-danger-bg)"
      : variant === "ghost" ? "transparent"
      : variant === "sm" ? "var(--c-btn-sm-bg)"
      : "var(--c-accent)",
    color:
      variant === "danger" ? "var(--c-danger-text)"
      : variant === "ghost" ? "var(--c-muted)"
      : variant === "sm" ? "var(--c-btn-sm-text)"
      : "var(--c-bg)",
    letterSpacing: "0.02em",
    transition: "opacity .15s, transform .1s",
    whiteSpace: "nowrap",
  }),
  progressTrack: { background: "var(--c-border)", borderRadius: "9999px", height: 8, overflow: "hidden" },
  th: { fontSize: 11, letterSpacing: "0.08em", textTransform: "uppercase", color: "var(--c-muted)", padding: "8px 12px", textAlign: "left", fontWeight: 600, borderBottom: "1px solid var(--c-border)" },
  td: { padding: "10px 12px", fontSize: 13, borderBottom: "1px solid var(--c-input-bg)", fontFamily: "'Geist Mono'" },
  pill: (color) => ({ display: "inline-flex", alignItems: "center", padding: "2px 8px", borderRadius: 6, fontSize: 10, fontWeight: 600, letterSpacing: "0.06em", background: color + "22", color }),
  overlay: {
    position: "fixed",
    inset: 0,
    background: "var(--c-overlay)",
    zIndex: 200,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    backdropFilter: "blur(8px)",
    WebkitBackdropFilter: "blur(8px)",
  },
  modal: {
    background: "var(--c-card)",
    border: "1px solid var(--c-border)",
    borderRadius: 20,
    padding: 28,
    width: "100%",
    maxWidth: 480,
    maxHeight: "85vh",
    overflowY: "auto",
    WebkitOverflowScrolling: "touch",
    boxShadow: "0 25px 60px rgba(0,0,0,0.35), 0 8px 24px rgba(0,0,0,0.15)",
  },
};
